blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # path('order_create', views.order, name='order_create'),
]

catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    # path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('osaka.urls')),
    path('account/', include('account.urls')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls')),
    path('feedback/', include('feedback.urls')),
    # path('send_email/', include('send_email.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from catalog.models import Product, Size
from django.core.validators import MaxValueValidator


class Promo(models.Model):
    promo = models.CharField(max_length=50)    
    percent = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    def __str__(self):
        return self.promo

    class Meta:
        verbose_name = 'Промо-код'
        verbose_name_plural = 'Промо-коды'

class Mart(models.Model):
    mart = models.CharField(max_length=70)    
    
    def __str__(self):
        return self.mart

    class Meta:
        verbose_name = 'Магазин'
        verbose_name_plural = 'Магазины'

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    mart = models.ForeignKey(Mart, on_delete=models.CASCADE, blank=True, null=True, default=1)
    address = models.CharField(max_length=250, blank=True, null=True)
    index = models.CharField(max_length=6, blank=True, null=True)
    promo = models.CharField(max_length=10, blank=True, null=True)   

    def __str__(self):
        return 'Номер заказа {}'.format(self.id)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='item')
    price = models.DecimalField(decimal_places=2, max_digits=10)
    quantity = models.IntegerField()
    size = models.ForeignKey(Size, on_delete=models.CASCADE, related_name='items')

cart/forms.py
from django import forms
from .models import Order, Mart

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    def __init__(self, sizes=[], *args, **kwargs):
        super(CartAddProductForm, self).__init__(*args, **kwargs)
        self.fields['size'] = forms.ChoiceField(choices=tuple([(str(name), str(name)) for name in sizes]))

    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(required=False, initial=False,
        widget=forms.HiddenInput)

class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['mart'] = forms.ModelChoiceField(queryset=Mart.objects.all(), empty_label='Выберете...', required=False)

    class Meta:
        model = Order
        fields = ['mart', 'address', 'index', 'promo']
        labels = {
            'mart': '',
            'address': '',
            'index': '',
            'promo': '',
        }
        widgets = {
            'mart': forms.TextInput(attrs={'class': 'editContent', 'option': 'Магазин'}),
            'address': forms.TextInput(attrs={'class': 'editContent', 'placeholder': 'Домашний адрес'}),
            'index': forms.TextInput(attrs={'class': 'editContent', 'placeholder': 'Почтовый индекс'}),
            'promo': forms.TextInput(attrs={'class': 'editContent', 'placeholder': 'Введите промо-код'})
        }

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST
from catalog.models import Category, Product, Size
from cart.models import Mart, OrderItem, Promo
from .cart import Cart
from .forms import CartAddProductForm, OrderForm
from django.core.exceptions import ObjectDoesNotExist


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    sizes = product.sizes.all()
    form = CartAddProductForm(sizes, request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
            quantity=cd['quantity'],
            size=cd['size'],
            update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request, **kwargs):  
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                    'update': True})
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('login')
        order_form = OrderForm(request.POST)

        # for item in cart:
            
        # cart.clear()
        # return redirect('cart:cart_detail')

        if order_form.is_valid():
            cd = order_form.cleaned_data    
            if len(cart):
                if cd['mart'] or cd['address']:                
                    new_order = order_form.save(commit=False)
                    new_order.user = request.user
                    new_order.save()
                    for item in cart:
                        size = Size.objects.get(size=item['size'])
                        try:
                            promo = Promo.objects.get(promo=cd['promo'])  
                        except ObjectDoesNotExist:
                            promo = None
                        if promo:
                            price = item['price'] - item['price'] * promo.percent / 100
                        else: 
                            price = item['price']
                        OrderItem.objects.create(order = new_order, 
                                                product = item['product'], 
                                                price =  price,
                                                quantity = item['quantity'],
                                                size = size)
                        product = item['product']
                        count = product.count - item['quantity']
                        if count <= 0:
                            product.count = 0
                        else:
                            product.count = count
                        product.save()
                        cart.clear()
                    return redirect('cart:cart_detail')

    else:
        order_form = OrderForm()
        return render(request, 'cart/detail.html', {'cart': cart, 'order_form': order_form})

cart/templates/cart/detail.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}Корзина{% endblock %}
{% block content %}
    <div class="container">
        <div class="card_main">
            <h1>Ваша корзина заказов</h1>
            <div class="card-flex">
                <table class="cart">
                    <thead>
                        <tr>
                            <th>Продукт</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th>Размер</th>
                            <th>Действие</th>
                            <th>Всего</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            {% with product=item.product %}
                            <tr class="table-item">
                                <td>
                                    <a href="{{ product.get_absolute_url }}">
                                        <img src="{% if product.image %}{{ product.image.url }}
                                        {% else %}{% static "osaka/images/empty.png" %}{% endif %}">
                                        <p>{{ product.name }}<p>
                                    </a>
                                </td>
                                <td class="num">{{ item.price }} ₽</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.size }}</td>
                                <td class="delete-btn"><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></td>
                                <td class="num">{{ item.total_price }} ₽</td>
                            </tr>
                            {% endwith %}
                        {% endfor %}
                            <tr class="text-col-1">
                                <td><a href="{% url "catalog:product_list" %}">Продолжить выбор товаров</a></td>
                            </tr>
                    </tbody>
                </table>
                <div class="offer-wrap">
                    <div class="offer">
                        <h1>Детали заказа</h1>
                        <div class="col-fields">
                            <div class="offer-col-1">
                                <p id="id_mart">Самовывоз:</p>
                                <p>Доставка:</p>
                                </br></br></br><p>Промо-код:</p>
                                <p>Итого:</p>
                            </div>
                            <div class="offer-col-2">
                                <form action="{% url 'cart:cart_detail' %}" method="post" id="offer-form">
                                    {{ order_form }}
                                    <div class="offer-col-2">
                                        <div class="total">
                                            <p>{{ cart.get_total_price }} ₽</p>
                                        </div>
                                    </div>
                                    
                            </div>
                        </div>

                    </div>
                        {% csrf_token %}
                        <button id="order-button">Оформить заказ</button>
                        </form>

                    <div class="text-col-2">
                        <div id="overlay">
                            <div id="text">Заказ оформлен!</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        var form = document.querySelector('#offer-form');
        var overlay = document.querySelector('#overlay');
        var address = form.querySelector('[name=address]');
        var mart = form.querySelector('[name=mart]');
        var product = document.querySelector('.table-item');
        var user_auth = document.querySelector('.user-auth');
        
        form.addEventListener('submit', function(e){
            e.preventDefault();
            if (user_auth) {
                if (product) {
                     if (address.value || mart.value) {
                        overlay.style.display = "block";
                    }
                }
            }
            else {
                window.location.replace("/account/login/");
            }
        })

        overlay.addEventListener('click', function(e){
            e.preventDefault();
            overlay.style.display = "none";
            form.submit();
        })

        window.addEventListener('keydown', function(e){
            if (e.keyCode == 27) { 
                e.preventDefault();
                overlay.style.display = "none";
                form.submit();
            }
        })

        
    </script> 
{% endblock %}