blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # path('order_create', views.order, name='order_create'),
]

catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    # path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
]

contact/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.subscription, name='contact'),
    path('mailing/<int:id>', views.mailing, name='mailing'),
]

feedback/urls.py
from django.urls import path
from . import views


app_name = 'feedback'

urlpatterns = [
    path('', views.contacts, name='contacts'),
    # path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('osaka.urls')),
    path('account/', include('account.urls')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls')),
    path('feedback/', include('feedback.urls')),
    # path('send_email/', include('send_email.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

osaka/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('track', views.track, name='track'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'),('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,
    related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    objects = models.Manager()
    published = PublishedManager()
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True, null=True)
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    class Meta:
        ordering = ('-publish',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('created',)
    def __str__(self):
            return 'Comment by {} on {}'.format(self.name, self.post)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

contact/models.py
from django.db import models


class Contact(models.Model):
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

class Mailing(models.Model):
    title = models.CharField(max_length=250)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Рассылки'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return self.title

osaka/models.py
from django.db import models

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ['email']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'editContent'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm

def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/list.html', {'posts': posts, 'section': 'blog'}) 
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html', {'page': page, 'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    return render(request,'blog/post/detail.html',{'post': post})
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        else:
            comment_form = CommentForm()
    return render(request,'blog/post/detail.html',{'post': post,
                                                    'comments': comments,
                                                    'new_comment': new_comment,
                                                    'comment_form': comment_form})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id,status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        post_url = request.build_absolute_uri(post.get_absolute_url())
        subject = '{} ({}) recommends you reading " {}"'.format(cd['name'], cd['email'], post.title)
        message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
        send_mail(subject, message, 'admin@myblog.com', [cd['to']])
        sent = True
    else:
        form = EmailPostForm()
        return render(request, 'blog/post/share.html',
        {'post': post, 'form': form})

contact/views.py
from .models import Contact, Mailing
from .forms import ContactForm
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.contrib.admin.views.decorators import staff_member_required

@require_POST
def subscription(request):
    cantact_form = ContactForm(request.POST)
    if cantact_form.is_valid():
        cd = cantact_form.cleaned_data
        email = cd["email"]
        try:
            contact = Contact.objects.get(email=email)
        except ObjectDoesNotExist:
            cantact_form.save()

        send_mail(
            'Вы подписались на рассылку.',
            'Мы будем информировать Вас о важных событиях и скидках нашего магазина. Промокод нового пользователя - OSAKASALE',
            'oskastore4you@gmail.com',
            [cd['email']],
            fail_silently=False,
        )

    return HttpResponseRedirect("/")

@staff_member_required
def mailing(request, id):
    contacts = Contact.objects.all()
    for contact in contacts:
        mailing = Mailing.objects.get(id=id)
        subject = mailing.title
        message = mailing.text
        send_mail(subject, message, 
            'oskastore4you@gmail.com', [contact.email])
    return HttpResponseRedirect("/admin/contact/mailing/")

osaka/views.py
from django.shortcuts import render
from catalog.models import Product


def index(request):
    discount_products = Product.objects.filter(discount__gt=0)[:8]
    return render(request, 'osaka/index.html', context={'section': 'index', 'products': discount_products})
    
def about(request):
    return render(request, 'osaka/about.html', context={'section': 'about'})

def track(request):
    return render(request, 'osaka/track.html', context={'section': 'track'})

osaka/templates/osaka/about.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}
    О нас
{% endblock %}

{% block rel %}
    <link rel="stylesheet" href="{% static 'osaka/css/banner.css' %}">
{% endblock %}

{% block content %}
    <div class="banner">
        <img src="{% static 'osaka/images/bg-02.jpg' %}">
        <p class="lead">О нас</p>
    </div>
    <div class="container">
        <div class="about-main-wrapper">
            <div class="about-wrapper">
                <div class="about-text">
                    <h1>О бренде</h1>
                    <p class="about about-skip"><span style="display:inline-block; width: 30px;"></span>Бренд одежды “OSAKA” была основан в начале нулевых годов, и лишь в этом 
                    году собирается выходить на международный рынок. “OSAKA” начал свой путь с одного маленького магазина 
                    с секонд хенд одеждой почти 20 лет назад. И сегодня это один из самых известных брендов по восточной 
                    культуре. Название бренда “OSAKA” берет свое название из Японского крупного портового и торгового 
                    города Осака, где автор и вдохновился созданием брендовой одежды. <p>
                    <p class="about about-skip"><span style="display:inline-block; width: 30px;"></span>Особенностью бренда являются лимитированные коллекции. Все началось от 
                    отсутствия денег и возможности шить много. В итоге это переросло в концепцию. Так же бренд не 
                    специализируется на мужской или женской одежде т.к. создатель бренда не видит в этом смысла и создает 
                    одежду сразу для всех (унисекс). Помимо стиля и дизайна мы придаем большое значение качеству ткани. 
                    Мы хотим, чтобы наши клиенты чувствовали себя комфортно.<p>
                </div>
                
                <div class="about-image about-img-1">
                    <img src="{% static "osaka/images/about-01.jpg" %}">
                </div>
            </div>

            <div class="about-wrapper">
                <div class="about-text">
                    <h1>О команде</h1>
                    <p class="about about-skip"><span style="display:inline-block; width: 30px;"></span>После того, как дизайн прототипирован, продукт официально входит в 
                    производственную цепочку. На этом этапе в игру вступает современное оборудование и профессиональная 
                    ручная работа.<p>
                    <p class="about about-skip"><span style="display:inline-block; width: 30px;"></span>Линия одежды «OSAKA» создается с помощью оборудования высокого качества. 
                    Мы с вниманием относимся к деталям и качеству, поэтому некоторые элементы одежды выполняются вручную, 
                    однако это также отражается на цене продукции.  Рубашки, брюки, футболки и другие элементы одежды 
                    выполнены в восточном стиле.</p>
                    <p class="about about-skip"><span style="display:inline-block; width: 30px;"></span>Прежде чем мы представим вам нашу продукцию, наши профессиональные 
                    дизайнеры проводят строгие проверки качества, чтобы утвердить каждый предмет одежды. Мы приглашаем 
                    моделей примерить одежду и рассмотреть общий вид. Мы постоянно модифицируем предметы одежды, пока 
                    внешний вид не станет идеальным. Наши продукты часто проходят многочисленные изменения и 
                    преобразования, прежде чем они поступят в продажу.</p>
                    <p class="about-quote"><i>Творчество просто соединяет вещи. Когда вы спрашиваете творческих людей, 
                    как они что-то сделали, они чувствуют себя немного виноватыми, потому что на самом деле они этого не 
                    делали, они просто что-то видели. Через некоторое время это показалось им очевидным.</i><br>
                    <label class="about-dark">- Мэрилин Менсон</label>
                    </p>
                </div>
                <div class="about-image about-img-2">
                    <img src="{% static "osaka/images/about-02.jpg" %}">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

osaka/templates/osaka/blog.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}
    Блог
{% endblock %}

{% block rel %}
    <link rel="stylesheet" href="{% static 'osaka/css/banner.css' %}">
{% endblock %}

{% block content %}
    <div class="banner">
        <img src="{% static 'osaka/images/bg-01.jpg' %}"/>
        <p class="lead">Блог</p>
    </div>
    <div class="container">
    <h1> Тут что-то будет</h>
    </div>
{% endblock %}

osaka/templates/osaka/contacts.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}
    Контакты
{% endblock %}

{% block rel %}
    <link rel="stylesheet" href="{% static 'osaka/css/banner.css' %}">
{% endblock %}

{% block content %}
    <div class="banner">
        <img src="{% static 'osaka/images/bg-03.jpg' %}">
        <p class="lead">Контакты</p>        
    </div>
    <div class="container">
    <div class="contact-main-wrapper">
        <div class="contact-wrapper">
            <label class="contact-title">Отправьте нам сообщение</label>
            <from>
                <input type="input" placeholder="Ваш e-mail адрес">
                <textarea type="text" placeholder="Как мы можем помочь?"></textarea>
                <button class="btn-sub2ch btn-contact">Отправить</button>
            </form>
        </div>
        <div class="contact-wrapper second-block">
            <p>Адрес</p>
            <p class="contact-text">Osaka Store улица капиталистов 228, первый корпус, второй этаж.</p>
            <p>Горячая линия</p>
            <p class="contact-text contact-number">+7 (913) 601 28-01</p>
            <p>Техническая поддержка</p>
            <p class="contact-text contact-number">support@osaka-store.com</p>
        </div>
    </div>
    </div>
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d18311.151647852286!2d73.3720874036499!3d54.99249322438609!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1623183218045!5m2!1sru!2sru" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
{% endblock %}

osaka/templates/osaka/index.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}
    Главная
{% endblock %}

{% block content %}



<div class="true_slider">
    <div class="slider middle">
        <div class="slides">
            <input type="radio" name="r" id="r1" checked>
            <input type="radio" name="r" id="r2">
            
            <div class="slide s1"><a href="http://osaka-store.xyz/catalog/rubashki/"><img src="{% static "osaka/images/slider/slide-02.jpg" %}" alt=""></a></div>
            <div class="slide"><a href="http://osaka-store.xyz/catalog/dzhinsovye-kurtki/"><img src="{% static "osaka/images/slider/slide-03.jpg" %}" alt=""></a></div>
        </div>

        <div class="navigation">
            <label for="r1" class="bar"></label>
            <label for="r2" class="bar"></label>  
        </div>
    </div>
</div>

<div class="container">
    <div class="col-extra-wrapper">
        <div class="col-extra"><img src="{% static "osaka/images/icons/chat.png" %}" alt="Картинка">Бесплатная доставка</div>
        <div class="col-extra"><img src="{% static "osaka/images/icons/coin.png" %}" alt="Картинка">100% возврат денег</div>
        <div class="col-extra col-extra__2"><img src="{% static "osaka/images/icons/delivery.png" %}" alt="Картинка">Горячая линия 24/7</div>
    </div>
</div>

<div class="container">
    <h1>Популярные категории</h1>
    <div id="main" class="product-list">

        <div class="card">
            <div class="item">
                <a href="http://osaka-store.xyz/catalog/Obuv/">
                    <img src="{% static "osaka/images/categories/category-1.jpg" %}" alt="Картинка">
                </a>
            </div>
        </div>

        <div class="card">
            <div class="item">
                <a href="http://osaka-store.xyz/catalog/topy/">
                    <img src="{% static "osaka/images/categories/category-2.jpg" %}" alt="Картинка">
                </a>
            </div>
        </div>

        <div class="card">
            <div class="item">
                <a href="http://osaka-store.xyz/catalog/hudi/">
                    <img src="{% static "osaka/images/categories/category-3.jpg" %}" alt="Картинка">
                </a>
            </div>
        </div>

        <div class="card">
            <div class="item">
                <a href="http://osaka-store.xyz/catalog/rubashki/">
                    <img src="{% static "osaka/images/categories/category-4.jpg" %}" alt="Картинка">
                </a>
            </div>
        </div>
    </div>
</div>

<div class="index-banner-2">
    <div class="banner">
        <img src = "{% static "osaka/images/bg-04.png" %}" alt="Картинка">
    </div>
</div>

<div class="container">
    <h1>Распродажа</h1>
    <div id="main" class="product-list">
        {% for product in products %}
        <div class="card">
            <div class="item">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "osaka/images/empty.png" %}{% endif %}">
            </a>
            </div>
            <p><a href="{{ product.get_absolute_url }}"> {{ product.name }}</a></p>
            {% if product.discount %}
            <div class="price">
                <p class="money discount">{{ product.price }} ₽ </p>
                <p class="money">{{ product.discount_calc }} ₽</p>
            </div>
            {% else %}
                <p class="money">{{ product.price }} ₽</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

osaka/templates/osaka/track.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}
    Отслеживание заказа
{% endblock %}

{% block content %}

<div class="container">
    <h1>Как долго длится процесс возврата?</h1>
<p>1. Мы с радостью принимаем возврат в течение 30 дней с момента получения для большинства товаров в новом состоянии.</p>
<p>2. Плата в размере 700 рублей будет вычтена из вашего возмещения за каждый возврат. (Подробнее см. В разделе «Как сделать возврат?»)</p>
<p>3. Если вы выберете Самостоятельную отправку для возврата посылки, вы самостоятельно несете расходы за обратную доставку.</p>
<h1>Каковы условия возврата?</h1>

<p>1. Если вы получаете поврежденные / бракованные товары или есть проблемы с качеством/размером, пожалуйста, свяжитесь со службой поддержки клиентов OSAKA и предоставьте подтверждающие фотографии, мы обработаем вашу заявку как можно скорее.</p>
<p>2. Предметы должны быть возвращены неношеными, нестираны, неповрежденными и со всеми оригинальными бирками. Если признаки этих действий будут обнаружены, стоимость товара возврату не подлежит.</p>
<p>3. К сожалению, мы не принимаем возвращенные товары, доставка которых не была оплачена. Возврат будет произведен за ваш счет.</p>
<p>4. Пожалуйста, не забудьте дважды проверить свои возвраты, прежде чем отправлять их. Мы не будем нести ответственность за возврат продуктов, не являющихся продуктами OSAKA</p>

<h1>Сколько времени занимает процесс возврата денег?</h1>
<p>Ваш запрос будет обработан в течение 5 рабочих дней после того, как мы получим ваше возврат.</p>
</div>

{% endblock %}

osaka/templates/osaka/wrapper.html
{% load static %}
{% load contact_tags %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'osaka/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'osaka/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'osaka/css/auth.css' %}">
    {% block rel %}{% endblock%}
</head>

<body>
<header>
    <div class="container-menu-desktop">
        <div class="container">
            <div class="menu-desktop">
                <a class="logo" href="{% url 'index' %}">
                    <span class="logo">osaka</span>
                </a>
                <ul class="main-menu" id="main-menu__nav">
                    <li {% if section == "index" %} class="selected" {% endif %}><a href="{% url 'index' %}">Главная</a></li>
                    <li {% if section == "catalog" %} class="selected" {% endif %}><a href="{% url 'catalog:product_list' %}">Каталог</a></li>
                    <li {% if section == "blog" %} class="selected" {% endif %}><a href="{% url 'blog:post_list' %}">Блог</a></li>
                    <li {% if section == "about" %} class="selected" {% endif %}><a href="{% url 'about' %}">О нас</a></li>
                    <li {% if section == "contacts" %}class="selected" {% endif %}><a href="{% url 'feedback:contacts' %}">Контакты</a></li>
                </ul>

                <div class="auth-menu">
                    <ul class="main-menu auth-block">
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                        <li class="user-auth"><a href="{% url "profile" %}">{{ request.user.username }}</a></li>
                        <li><a href="{% url "logout" %}">Выйти</a></li>
                        {% else %}
                        <li><a class="main-cart" href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                        <li {% if section == "sign-in" %} class="selected" {% endif %}><a href="{% url 'login' %}">Вход</a></li>
                        <li {% if section == "register" %} class="selected" {% endif %}><a href="{% url 'register' %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <ul class="burger">
        <li {% if section == "index" %} class="selected" {% endif %}><a href="{% url 'index' %}">Главная</a></li>
        <li {% if section == "catalog" %} class="selected" {% endif %}><a href="{% url 'catalog:product_list' %}">Каталог</a></li>
        <li {% if section == "blog" %} class="selected" {% endif %}><a href="{% url 'blog:post_list' %}">Блог</a></li>
        <li {% if section == "about" %} class="selected" {% endif %}><a href="{% url 'about' %}">О нас</a></li>
        <li {% if section == "contacts" %} class="selected" {% endif %}><a href="{% url 'feedback:contacts' %}">Контакты</a></li>
    </ul> 
</header>

<div class="main-content">
    <section>
        {% block content %} {% endblock %}
    </section>
        {% block review %} {% endblock %}
</div>

<footer>
    <div class="container">
        <div class="column">
            <ul class="col1">
                <li class="list-name">Социальные сети</li>
                <li><a href="https://www.instagram.com/osakastorexyz/?utm_medium=copy_link">Instagram</a></li>
                <li><a href="https://vk.com/public205342174">Вконтакте</a></li>
                <li><a href="https://twitter.com/Osaka68307259">Twitter</a></li>
            </ul>
            <ul class="col2">
                <li class="list-name">Помощь</li>
                <li><a href="{% url 'track' %}">Возврат</a></li>
            </ul>
            <ul class="col3">
                <li class="list-name">Обратная связь</li>
                <li>
                    <p>Возник вопрос? Позвоните нам <br> по номеру +7 (913) 601 28-01</p>
                </li>
            </ul>
            <ul class="col4">
                <li class="list-name">Рассылка</li>
                    <form action='{% url 'contact' %}' method='post'>
                        {% csrf_token %}
                        {{ contact_form }}
                        <li><input class="input-sub" type="text" name="email" placeholder="email@example.com"></li>
                        <li><button class="btn-sub" type="submit">Подписаться</button></li>
                    </form> 
                </li>
            </ul>
        </div>
        <p class="txt-center">© 2021 Osaka-store. Все права защищены</p>
    </div>
</footer>
</body>

</html>