blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    # path('order_create', views.order, name='order_create'),
]

catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    # path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('osaka.urls')),
    path('account/', include('account.urls')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls')),
    path('feedback/', include('feedback.urls')),
    # path('send_email/', include('send_email.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from polymorphic.models import PolymorphicModel

class Size(models.Model):
    size = models.CharField(max_length=200)

    def __str__(self):
        return self.size

class ClothesSize(Size):
    class Meta:
        verbose_name = 'Размеры одежды'
        verbose_name_plural = 'Размеры одежды'

class ShoesSize(Size):
    class Meta:
        verbose_name = 'Размеры обуви'
        verbose_name_plural = 'размеры обуви'

class Category(PolymorphicModel):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_list_by_category', args=[self.slug])

class ClothesCatrgory(Category):
    class Meta:
        verbose_name = 'Категории одежды'
        verbose_name_plural = 'Категории одежды'
    
class ShoesCategory(Category):
    class Meta:
        verbose_name = 'Категории обуви'
        verbose_name_plural = 'Категории обуви'

class Product(PolymorphicModel):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(blank=True)
    description = models.TextField(blank=True)
    count = models.IntegerField(null=True)
    discount = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse('catalog:product_detail', args=[self.id, self.slug])
    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def discount_calc(self):
        return self.price - (self.price * self.discount / 100)

class Clothes(Product):
    category = models.ForeignKey(ClothesCatrgory, related_name='products',
        on_delete=models.CASCADE)
    sizes = models.ManyToManyField(ClothesSize, related_name='products')
    class Meta:
        verbose_name = 'Одежда'
        verbose_name_plural = 'Одежда'

class Shoes(Product):
    category = models.ForeignKey(ShoesCategory, related_name='products',
        on_delete=models.CASCADE)
    sizes = models.ManyToManyField(ShoesSize, related_name='products')
    class Meta:
        verbose_name = 'Обувь'
        verbose_name_plural = 'Обувь'

class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

catalog/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['text']
        labels = {
            'text': ''
        }
        widgets = {
            'text': forms.Textarea()
        }

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from django.db.models import Q
from cart.forms import CartAddProductForm
from .forms import ReviewForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(Q(clothes__category__name=category.name) | Q(shoes__category__name=category.name))
    filter_by = request.GET.get('filter_by')
    if filter_by:
        if filter_by == 'gt':
            products = products.order_by('price')
        else:
            products = products.order_by('-price')

    return render(request, 'catalog/list.html',
                {'category': category,
                'categories': categories,
                'products': products,
                'section': 'catalog'})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    reviews = product.reviews.order_by('-date')
    sizes = product.sizes.all()
    cart_product_form = CartAddProductForm(sizes=sizes)
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            new_comment = review_form.save(commit=False)
            new_comment.product = product
            new_comment.author = request.user
            new_comment.save()
            return redirect(product.get_absolute_url())
    else:
        review_form = ReviewForm()
    return render(request, 'catalog/detail.html',
        {'product': product, 'reviews': reviews, 
        'review_form': review_form,
        'cart_product_form': cart_product_form})
    

catalog/templates/catalog/detail.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}
    Товары
{% endblock %}

{% block content %}
<div class="container">
    <div class="detail_card_block">
        <div class="detail_card">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "osaka/images/empty.png" %}{% endif %}">
        </div>
        <div class="detail_card">
            <h1><p>{{ product.name }}</p></h1>


{% if product.discount %}
            <div class="price">
                <p class="cash_discount">{{ product.price }} ₽ </p>
                <p class="cash">{{ product.discount_calc }} ₽</p>
            </div>
            {% else %}
                <p class="cash">{{ product.price }} ₽</p>
            {% endif %}
            <p class="description">{{ product.description }}</p>
            <p class="description">Количество на складе: {{ product.count }}</p>
            <form action="{% url "cart:cart_add" product.id %}" method="post">     
            {% csrf_token %}
                {{ cart_product_form }}
                <button class="btn-sub2ch" {% if product.count == 0 %} disabled {% endif %}>Добавить в корзину</button>
            
            </form>
            {% endblock %}
            {% block review %}
            <section class="review">
                <div class='container'>
                        {% if request.user.is_authenticated %}
                                <h1>Оставить отзыв</h1>
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ review_form }}
                                <button class="btn-sub2ch btn-review">Отправить</button>
            </form>
                {% endif %} 
                    <h1>Отзывы</h1>
                    {% for review in reviews %}
                        <p class="review_author">{{ review.author }}<label>{{ review.date }}</label></p>
                        <p class="review_text">{{ review.text }}</p>
                    {% endfor %}  
                </div>
            </section>
            {% endblock %}
        </div>
    </div>
</div>

catalog/templates/catalog/list.html
{% extends 'osaka/wrapper.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}

{% block content %}
<div class="container">
    <div id="sidebar">
        <ul>
            <li {% if not category %} class = "selected" {% endif %}><a href="{% url "catalog:product_list" %}" id="full_list">Все товары</a></li>
            {% for c in categories %}
            <li {% if category.slug == c.slug %} class = "selected" {% endif %}><a href="{{ c.get_absolute_url }}">{{ c.name }}</a></li>
            {% endfor %}
        </ul>
    </div>

    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="ABOBA">
        <p>Цена по:<a href='{{ request.path }}?filter_by=lt'>убыванию</a><a href='{{ request.path }}?filter_by=gt'>возрастанию</a></p>
    </div>

    
    <div id="main" class="product-list">
        {% for product in products %}
        <div class="card">
            <div class="item">
            <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "osaka/images/empty.png" %}{% endif %}">
            </a>
            </div>
            <p><a href="{{ product.get_absolute_url }}"> {{ product.name }}</a></p>
            {% if product.discount %}
            <div class="price">
                <p class="money discount">{{ product.price }} ₽ </p>
                <p class="money">{{ product.discount_calc }} ₽</p>
            </div>
            {% else %}
                <p class="money">{{ product.price }} ₽</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}